name: Foo
on:
  workflow_dispatch:

jobs:
  print-git-settings-on-windows:
    runs-on: windows-latest
    steps:
      - run: |
          git config --global --get core.autocrlf || echo "(unset)"
          git config --global --get core.eol || echo "(unset)"
